Load VS Code earlier.
concrete-utopia/utopia pull request #1794
Opened 2021-09-06 16:15 UTC by seanparsons

Fixes #1793

**Problem:**
Currently the VS Code iframe loads quite late, but makes about 1/3 of the requests during the startup of the editor including a few sizeable downloads.

**Fix:**
The iframe is now loaded effectively immediately as a value for `vscodeBridgeId` will now be available immediately and cannot be null.

An additional fix was made which potentially only helps locally as it delays the property controls component from starting up until the VS Code bridge is ready. As it was blocking execution on the main thread which delayed the VS Code iframe from opening.

**Commit Details:**
- Fixes #1793.
- `EditorState.vscodeBridgeId` is now not nullable and a value is
  always supplied to it during startup.
- The `CodeEditorWrapper` now does not wait for the bridge to be
  marked as ready.
- The `PropertyControlsInfoComponent` holds off from starting up
  until the VS Code bridge is ready.

2021-09-06 16:21 UTC, balazsbajorics approved these changes
looks legit. however, the VSCode iframe still only starts loading once the editor first renders. 

in Discord last week we talked about trying to append a dummy vscode iframe to the editor template html, to see if it helps with first load time (basically acting as a prefetch for Chrome)? or appending the iframe, and then instead of destroying it and creating the 'real' iframe, try to somehow keep the one iframe alive and move it to a new position in the HTML document?

if you haven't looked into those yet, can you make a follow-up ticket for that?

2021-09-06 16:37 UTC, seanparsons commented
> in Discord last week we talked about trying to append a dummy vscode iframe to the editor template html, to see if it helps with first load time (basically acting as a prefetch for Chrome)? or appending the iframe, and then instead of destroying it and creating the 'real' iframe, try to somehow keep the one iframe alive and move it to a new position in the HTML document?

I did look into this, the issues I could see:
- Having a dummy iframe means that the real iframe loads at some indeterminate point later, which means there _may_ be some benefit in loading if the timing is just right. But if the timing is slightly off we end up making two requests to a lot of the VS Code components thereby slowing down.
- Shifting the iframe makes me a little nervous, as we'd have to make it not display via zero-sizing or some such and potentially while VS Code is initialising shunt it to a different part of the DOM. With that being done by some weird side effect'y component.
- Having VS Code queue up a bunch of downloads during the editor download is entirely likely to make the main editor load slower because it will be sharing that same downstream.

2021-09-07 09:07 UTC, Rheeseyb commented on editor/src/components/editor/editor-component.tsx
> +          <PropertyControlsInfoComponent />
Can you add a comment to this line please, because I can definitely see us forgetting why we're reliant on `props.vscodeBridgeReady` here

2021-09-07 09:16 UTC, Rheeseyb requested changes
In `actions.ts` we update the `vscodeBridgeId` when setting the project ID, [only if it is null](https://github.com/concrete-utopia/utopia/blob/master/editor/src/components/editor/actions/actions.ts#L3433), so that will never happen any more. Because of this, it means VS Code won't connect to the correct IndexedDB store when the project ID is first set (i.e. when creating an empty project). I've just tested and it seems to work when reloading the editor after creating an empty project, probably because at that point a project ID exists from the beginning

2021-09-07 09:42 UTC, seanparsons commented
> In `actions.ts` we update the `vscodeBridgeId` when setting the project ID, [only if it is null](https://github.com/concrete-utopia/utopia/blob/master/editor/src/components/editor/actions/actions.ts#L3433), so that will never happen any more. Because of this, it means VS Code won't connect to the correct IndexedDB store when the project ID is first set (i.e. when creating an empty project). I've just tested and it seems to work when reloading the editor after creating an empty project, probably because at that point a project ID exists from the beginning

Fixed in e14d0689.

2021-09-07 10:00 UTC, seanparsons commented
> In `actions.ts` we update the `vscodeBridgeId` when setting the project ID, [only if it is null](https://github.com/concrete-utopia/utopia/blob/master/editor/src/components/editor/actions/actions.ts#L3433), so that will never happen any more. Because of this, it means VS Code won't connect to the correct IndexedDB store when the project ID is first set (i.e. when creating an empty project). I've just tested and it seems to work when reloading the editor after creating an empty project, probably because at that point a project ID exists from the beginning

Fixed in 3615bbd6.

2021-09-07 10:21 UTC, Rheeseyb approved these changes

2021-09-07 10:49 UTC, merged