Delete existing empty spans when leaving text edit mode
concrete-utopia/utopia pull request #4266
Opened 2023-09-28 16:43 UTC by ruggi

Fixes #4265

**Problem:**

When leaving text edit mode, new elements are deleted, but existing ones are kept.

**Fix:**

Make the behavior equal for both new and existing elements.

2023-09-28 23:07 UTC, balazsbajorics requested changes
I tried the try me link and something is very broken, the Enter acts like a delete button for divs that don't already contain text, and text insertion also immediately quits.

Bug aside, I think for non-new elements we should be more careful, and make sure it's a span and not a div and/or that it doesn't have dimensions, backgroundColor, etc. So in general, we want the feature to clean up invisible leftover, but do not cause a headache if you have something selected and you accidentally press Enter.

2023-09-29 08:42 UTC, ruggi commented
> I tried the try me link and something is very broken, the Enter acts like a delete button for divs that don't already contain text, and text insertion also immediately quits.
> 
> Bug aside, I think for non-new elements we should be more careful, and make sure it's a span and not a div and/or that it doesn't have dimensions, backgroundColor, etc. So in general, we want the feature to clean up invisible leftover, but do not cause a headache if you have something selected and you accidentally press Enter.

Updated - the behavior only triggers for span elements without styling nor event handlers!

2023-09-29 14:16 UTC, balazsbajorics approved these changes

2023-10-02 07:23 UTC, bkrmendy approved these changes

2023-10-02 07:24 UTC, merged