Gap controls positioned to be consistent with element positions.
concrete-utopia/utopia pull request #4412
Opened 2023-10-20 13:32 UTC by seanparsons

**Problem:**
With pretty much anything other than elements that are full width/height in a flex container, the gap controls are invariably in an odd place like over on the left hand side when the content is aligned to the centre:
![image](https://github.com/concrete-utopia/utopia/assets/217400/0407a615-a5e2-4bdc-a9fb-2da6ac797398)

**Cause:**
The handles were centred in a div which was only _sized_ to that of the bounds of the children, so in the case of centre aligned elements the handles would be centred inside the div that was positioned on left at position 0 (for instance).

**Fix:**
By positioning the containing div for the handles against the accumulated boundary of the children, the handles end up centred against those positions instead, which means they are now in the right place:
![image](https://github.com/concrete-utopia/utopia/assets/217400/249750b3-9992-4876-b087-62c954ecec74)

**Commit Details:**
- `contentArea` in `FlexGapControl` is now a `CanvasRectangle` so that the position of the children as a whole can be utilised.
- `GapControlSegment` now uses the newly provided fields in `contentArea` to position the containing div so that the handles centered within it are centered against the bounds of the content.

2023-10-20 14:24 UTC, ruggi approved these changes

2023-10-23 09:31 UTC, Rheeseyb approved these changes

2023-10-23 09:39 UTC, bkrmendy requested changes
The controls are not positioned correctly when the element has padding (see this project: https://utopia.pizza/p/21453729-habitual-strawflower/?branch_name=fix-gap-control-positioning), also the PR is missing tests

2023-10-23 17:09 UTC, bkrmendy approved these changes

2023-10-23 17:40 UTC, ruggi approved these changes

2023-10-24 07:39 UTC, balazsbajorics approved these changes

2023-10-24 09:24 UTC, Rheeseyb approved these changes

2023-10-24 09:46 UTC, merged