Remove unused imports in `removeElementAtPath`
concrete-utopia/utopia pull request #4668
Opened 2023-12-19 19:26 UTC by liady

**Problem:**
When inserting a new element using drag&draw - the import for this element remains in `storyboard.js` (even if the element itself is being inserted elsewhere).

**Cause:**
We are not removing unused imports when we call `removeElementAtPath`

**Fix:**
Adding the ability to remove unused imports inside `removeElementAtPath` - if are not used anymore

2023-12-20 11:48 UTC, ruggi approved these changes

2024-01-02 16:32 UTC, seanparsons approved these changes

2024-01-04 10:33 UTC, Rheeseyb commented on editor/src/components/editor/import-utils.ts
> +  element: JSXElement,
Minor point here, but I'd suggest renaming this to `removedElement`, and possibly even renaming the function to reflect that this is removing unused imports specifically for that removed element

2024-01-04 14:38 UTC, liady commented
Tests are passing but I want to check some edge case that popped up (with the worker update) before merging.

2024-01-04 14:50 UTC, Rheeseyb requested changes
As discussed, this causes a breaking issue when dragging to insert

2024-01-04 15:57 UTC, liady commented
> As discussed, this causes a breaking issue when dragging to insert

Fixed (not removing the imports when reparenting the same file)

2024-01-10 09:47 UTC, balazsbajorics approved these changes

2024-01-10 14:20 UTC, merged