chore/remove `domtoimage`
concrete-utopia/utopia pull request #4812
Opened 2024-01-30 17:22 UTC by liady

**Problem:**
`domtoimage` caused issues when it was imported as an external inside a web worker.

**Fix:**
The underlying externals issue still remains, but we removed `domtoimage` as we don't use it anymore (and it was our only external dependecy)

2024-01-30 17:37 UTC, balazsbajorics approved these changes

2024-01-31 10:55 UTC, Rheeseyb approved these changes

2024-01-31 11:00 UTC, seanparsons commented on editor/pnpm-lock.yaml
Weird, the lock file got much bigger as a result of removing something...

2024-01-31 11:01 UTC, seanparsons approved these changes

2024-01-31 11:17 UTC, balazsbajorics commented on editor/pnpm-lock.yaml
oh this _is_ weird!

2024-01-31 11:30 UTC, balazsbajorics commented on editor/pnpm-lock.yaml
Liad did you run this in our nix environment? maybe you had a different node version or a different `pnpm` version that caused the lockfile to be re-done

2024-01-31 11:31 UTC, balazsbajorics requested changes
blocking this until we figure out the huge lockfile change

2024-01-31 12:17 UTC, liady commented on editor/pnpm-lock.yaml
yes, I ran it in our nix environment, I removed some dependencies so expected a lockfile diff, but you're right that the lockfile result seems weird. Will check it again.

2024-01-31 12:20 UTC, liady commented on editor/pnpm-lock.yaml
Seems like it's mostly prettier changes 
<img width="743" alt="image" src="https://github.com/concrete-utopia/utopia/assets/7003853/15897b3d-44be-43f8-a322-76b22c3b15be">
<img width="681" alt="image" src="https://github.com/concrete-utopia/utopia/assets/7003853/09a65123-edeb-4769-b7a0-4a2908f01de6">

2024-01-31 13:19 UTC, balazsbajorics approved these changes

2024-01-31 13:19 UTC, balazsbajorics commented on editor/pnpm-lock.yaml
thanks!

2024-01-31 13:40 UTC, merged