Project Page Review and More Radix Components
concrete-utopia/utopia pull request #5028
Opened 2024-03-13 04:29 UTC by lankaukk

_...many updates loading..._

2024-03-14 10:26 UTC, seanparsons commented on utopia-remix/app/components/projectActionContextMenu.tsx
> +                          /* eslint-disable-next-line react/jsx-no-bind */
Why does this rule need to be disabled?

2024-03-15 09:47 UTC, ruggi requested changes
The code looks good overall 👍 

However the `setRequestAccess` logic which needs updating otherwise that poor server will explode in a million shards 😅

2024-03-15 09:47 UTC, ruggi commented on utopia-remix/app/components/projectActionContextMenu.tsx
> +                    /* eslint-disable-next-line react/jsx-no-bind */
I think this has already been fixed on master, could you update/remove it?

2024-03-15 09:47 UTC, ruggi commented on utopia-remix/app/components/projectActionContextMenu.tsx
> +                      {pendingAccessRequests.length > 0 ? (
```ts
when(pendingAccessRequests.length > 0, ...
```

2024-03-15 09:47 UTC, ruggi commented on utopia-remix/app/components/projectActionContextMenu.tsx
> +              /* eslint-disable-next-line react/jsx-no-bind */
this one should also go

2024-03-15 09:47 UTC, ruggi commented on utopia-remix/app/routes/projects.tsx
> +    }, [accessRequestsFetcher, project])
This is causing/will cause an endless loop of requests to that fetcher! 😱 
1. The effect should not submit the fetcher, but instead _only_ be used to process new data on the fetcher (lines 605-609)
2. The submit should only happen on an explicit action – I think the right place would when the context menu is opened, see https://github.com/concrete-utopia/utopia/blob/4bbd34c90173a22e7d13a1cb13641c4a64a08f44/utopia-remix/app/routes/projects.tsx#L905-L906

2024-03-15 15:17 UTC, Rheeseyb approved these changes

2024-03-15 15:21 UTC, merged