Ux/inspector rearrange
concrete-utopia/utopia pull request #892
Opened 2021-01-27 11:09 UTC by OmarDaSilva

Rearranged the inspector

2021-01-28 15:18 UTC, seanparsons approved these changes

2021-02-09 11:49 UTC, OmarDaSilva commented
This PR is ready to be merged, could I get approvers or more comments, please?

2021-02-09 12:42 UTC, balazsbajorics commented on editor/src/components/inspector/inspector.tsx
> +  //first
I'd remove this comment from here

```suggestion
```

2021-02-09 12:42 UTC, enidemi commented on editor/src/components/inspector/sections/style-section/style-section.tsx
> +  FlexRow,
these imports seem unused, can you please delete them? :)

2021-02-09 12:44 UTC, balazsbajorics commented on editor/src/components/inspector/sections/event-handlers-section/event-handlers-section.tsx
> +    <React.Fragment>
`<>` is actually a shorthand version to write `<React.Fragment>`

in some places in the codebase we use `<React.Fragment>` if we also use Emotion's css pragma (how to see if the pragma is used: the first line of a file will contain `/** @jsx jsx */` ). In other files, it is not necessary to write React.Fragment, you can use the `<></>` shorthand too.

2021-02-09 12:44 UTC, balazsbajorics commented on editor/src/components/inspector/sections/style-section/style-section.tsx
> +import { InspectorContextMenuWrapper } from '../../../../uuiui-deps'
it seems like all these new imports were not used in the end, please remove them

2021-02-09 12:45 UTC, enidemi approved these changes

2021-02-09 12:45 UTC, balazsbajorics requested changes
please remove that leftover comment and unnecessary imports, otherwise looks good! :)

2021-02-09 12:56 UTC, OmarDaSilva commented on editor/src/components/inspector/inspector.tsx
> +  //first
Done!

2021-02-09 15:46 UTC, balazsbajorics approved these changes

2021-02-09 17:07 UTC, merged